services:

  nginx:
    image: nginx
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    container_name: "nginx"
    links:
      - app_serv1:app_serv1
      - app_serv2:app_serv2
      - app_serv3:app_serv3
    depends_on:
      - app_serv1
      - app_serv2
      - app_serv3
    volumes:
      - ./nginx:/nginx
    networks:
      - app_network
    ports:
      - "8080:80"

  app_serv1:
    image: node:16
    build:
      context: ./app_serv
      dockerfile: ./Dockerfile
    container_name: "app_serv1"
    volumes:
      - ./app_serv:/app_serv
    networks:
      - app_network
    ports:
      - "8080"
    environment:
      - INSTANCE=serv1
  
  app_serv2:
    image: node:16
    build:
      context: ./app_serv
      dockerfile: ./Dockerfile
    container_name: "app_serv2"
    volumes:
      - ./app_serv:/app_serv
    networks:
      - app_network
    ports:
      - "8080"
    environment:
      - INSTANCE=serv2

  app_serv3:
    image: node:16
    build:
      context: ./app_serv
      dockerfile: ./Dockerfile
    container_name: "app_serv3"
    volumes:
      - ./app_serv:/app_serv
    networks:
      - app_network
    ports:
      - "8080"
    environment:
      - INSTANCE=serv3

  couchdb:
    image: couchdb
    build:
      context: ./couchdb
      dockerfile: ./Dockerfile
    container_name: "couchdb"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
      - ./data:/opt/couchdb/data
      - ./couchdb:/couchdb
    ports:
      - "8082:5984"
    #http://localhost:8082/_utils/#/_all_dbs

  rabbitmq:
    image: rabbitmq
    build:
      context: ./rabbitmq
      dockerfile: ./Dockerfile
    container_name: "rabbitmq"
    volumes:
      - ./rabbitmq:/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "8083:5672"
      - "8084:15672"

  logger:
    image: node:16
    build:
      context: ./logger
      dockerfile: ./Dockerfile
    container_name: "logger"
    volumes:
      - ./logger:/logger
    # ports:
    #   - "8085:8080"
  
networks:
  app_network:
    driver: bridge