services:

  nginx:
    image: nginx
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    container_name: "nginx"
    ports:
      - "8080:80"

  app_serv:
    image: node:16
    build:
      context: ./app_serv
      dockerfile: ./Dockerfile
    container_name: "app_serv"
    ports:
      - "8081:8080"

  couchdb:
    image: couchdb
    build:
      context: ./couchdb
      dockerfile: ./Dockerfile
    container_name: "couchdb"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
      - ./data:/opt/couchdb/data
    ports:
      - "8082:5984"

  rabbitmq:
    image: rabbitmq
    build:
      context: ./rabbitmq
      dockerfile: ./Dockerfile
    container_name: "rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "8083:5672"
      - "8084:15672"

  logger:
    image: node:16
    #build:
      #context: ./logger
      #dockerfile: ./Dockerfile
    container_name: "logger"
    # ports:
    #   - "8085:8080"
    